### ISSUE TITLE
ValueError: incomplete format

### ISSUE THREAD

**Issue by tibor95** [MartinThoma/memtop#2]
Hi,

when running memtop -v -p 1 I get

```
 RAM use without cached pages: 74.1% , SWAP use: 66.8%
Traceback (most recent call last):
  File "/usr/bin/memtop", line 27, in <module>
    memtop.main()
  File "/usr/lib/python3.4/site-packages/memtop/__init__.py", line 502, in main
    check_swapping(verbose)
  File "/usr/lib/python3.4/site-packages/memtop/__init__.py", line 224, in check_swapping
    round(_IOwaitprc, 1)))
ValueError: incomplete format
```

regards

**Comment by MartinThoma** [comment]
Thank you for the report. I just forgot a `%`. The issue is fixed and a new version is available via PyPI.
